Fix `cargo test --no-default-features`
TedDriggs/darling pull request #284
Opened 2024-04-09 11:52 UTC by mgeisler

The suggestion is not given when the `suggestions` Cargo feature is disabled.

2024-04-09 13:01 UTC, TedDriggs requested changes

2024-04-09 13:01 UTC, TedDriggs commented on tests/flatten.rs
> +#[cfg(features = "suggestions")]
```suggestion
#[cfg(feature = "suggestions")]
```

Per clippy, this is invalid as-written.

2024-04-11 17:19 UTC, TedDriggs approved these changes

2024-04-11 17:19 UTC, TedDriggs commented
Now the one open question in my mind - why didn't CI catch this before? Don't need to block this PR for it, but do need to sort that out.

2024-04-11 17:19 UTC, merged

2024-04-12 18:26 UTC, mgeisler commented
> Now the one open question in my mind - why didn't CI catch this before? Don't need to block this PR for it, but do need to sort that out.

I think it's because you're not running all tests with `--no-default-features`, only the ones in `core/` if I read [`ci.yml`](https://github.com/TedDriggs/darling/blob/master/.github/workflows/ci.yml#L36) correctly